package com.examonline.service;

import com.examonline.domain.AppUser;
import com.examonline.domain.ExamPaper;
import com.examonline.domain.PaperQuestion;
import com.examonline.domain.Question;
import com.examonline.domain.SchoolClass;
import com.examonline.repo.AppUserRepository;
import com.examonline.repo.ExamPaperRepository;
import com.examonline.repo.PaperQuestionRepository;
import com.examonline.repo.QuestionRepository;
import com.examonline.repo.SchoolClassRepository;
import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

@Component
public class InitDataService {
    private final AppUserRepository userRepository;
    private final SchoolClassRepository classRepository;
    private final QuestionRepository questionRepository;
    private final ExamPaperRepository paperRepository;
    private final PaperQuestionRepository paperQuestionRepository;
    private final JsonSupport jsonSupport;

    public InitDataService(AppUserRepository userRepository,
                           SchoolClassRepository classRepository,
                           QuestionRepository questionRepository,
                           ExamPaperRepository paperRepository,
                           PaperQuestionRepository paperQuestionRepository,
                           JsonSupport jsonSupport) {
        this.userRepository = userRepository;
        this.classRepository = classRepository;
        this.questionRepository = questionRepository;
        this.paperRepository = paperRepository;
        this.paperQuestionRepository = paperQuestionRepository;
        this.jsonSupport = jsonSupport;
    }

    @PostConstruct
    public void init() {
        if (userRepository.count() > 0) {
            return;
        }
        SchoolClass c1 = new SchoolClass();
        c1.setName("计算机 2301 班");
        c1.setDepartment("计算机学院");
        c1.setMajor("软件工程");
        c1.setStudentCount(40);
        classRepository.save(c1);

        AppUser admin = new AppUser();
        admin.setUsername("admin");
        admin.setPassword("admin123");
        admin.setRole("ADMIN");
        admin.setRealName("系统管理员");
        admin.setDepartment("教务处");
        admin.setEnabled(true);
        userRepository.save(admin);

        AppUser teacher = new AppUser();
        teacher.setUsername("teacher");
        teacher.setPassword("teacher123");
        teacher.setRole("TEACHER");
        teacher.setRealName("张老师");
        teacher.setEmployeeNo("T1001");
        teacher.setDepartment("计算机学院");
        teacher.setEnabled(true);
        userRepository.save(teacher);

        AppUser student = new AppUser();
        student.setUsername("student");
        student.setPassword("student123");
        student.setRole("STUDENT");
        student.setRealName("李同学");
        student.setStudentNo("S2023001");
        student.setClassName(c1.getName());
        student.setDepartment(c1.getDepartment());
        student.setMajor(c1.getMajor());
        student.setEnabled(true);
        userRepository.save(student);

        List<Question> questions = List.of(
                question("Java 中用于表示继承的关键字是？", "SINGLE_CHOICE", "Java", "面向对象", "EASY", List.of("A. extends", "B. implements", "C. this", "D. super"), "A", 5, "extends 用于类继承"),
                question("以下哪些属于 Java 集合框架？", "MULTI_CHOICE", "Java", "集合", "MEDIUM", List.of("A. List", "B. Set", "C. Map", "D. Thread"), "A,B,C", 10, "前三项属于集合"),
                question("JVM 负责 Java 程序的运行。", "TRUE_FALSE", "Java", "JVM", "EASY", List.of("A. 正确", "B. 错误"), "A", 5, null),
                question("Spring Boot 默认内嵌的 Web 容器是什么？", "FILL_BLANK", "Spring", "基础", "EASY", List.of(), "Tomcat", 5, null),
                question("简述 MVC 模式的三个组成部分。", "SHORT_ANSWER", "软件工程", "架构", "MEDIUM", List.of(), "Model View Controller", 10, "答出核心词即可")
        );
        questions.forEach(questionRepository::save);

        ExamPaper paper = new ExamPaper();
        paper.setTitle("Java 基础测试卷");
        paper.setDurationMinutes(90);
        paper.setPassScore(60);
        paper.setStartTime(LocalDateTime.now().minusDays(1));
        paper.setEndTime(LocalDateTime.now().plusDays(7));
        paper.setPublished(true);
        paper.setAutoGenerated(false);
        paper.setTargetClassesJson(jsonSupport.toJson(List.of(c1.getName())));
        paper.setTotalScore(0);
        paper = paperRepository.save(paper);
        int total = 0;
        for (int i = 0; i < questions.size(); i++) {
            Question q = questions.get(i);
            PaperQuestion item = new PaperQuestion();
            item.setPaperId(paper.getId());
            item.setQuestionId(q.getId());
            item.setOrderNo(i + 1);
            item.setScore(q.getScore());
            item.setQuestionSnapshotJson(jsonSupport.toJson(jsonSupport.toQuestionView(q)));
            paperQuestionRepository.save(item);
            total += q.getScore();
        }
        paper.setTotalScore(total);
        paperRepository.save(paper);
    }

    private Question question(String title, String type, String subject, String knowledgePoint, String difficulty, List<String> options, String answer, int score, String explanation) {
        Question q = new Question();
        q.setTitle(title);
        q.setType(type);
        q.setSubject(subject);
        q.setKnowledgePoint(knowledgePoint);
        q.setDifficulty(difficulty);
        q.setOptionsJson(jsonSupport.toJson(options));
        q.setCorrectAnswer(answer);
        q.setScore(score);
        q.setExplanation(explanation);
        q.setCreatorUsername("teacher");
        return q;
    }
}

