package com.examonline.service;

import com.examonline.domain.ExamPaper;
import com.examonline.domain.Question;
import com.examonline.web.dto.BasicDtos;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class JsonSupport {
    private final ObjectMapper objectMapper;

    public JsonSupport(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("JSON serialize failed", e);
        }
    }

    public List<String> readStringList(String json) {
        if (json == null || json.isBlank()) {
            return List.of();
        }
        try {
            return objectMapper.readValue(json, new TypeReference<>() {});
        } catch (Exception e) {
            throw new IllegalStateException("JSON parse failed", e);
        }
    }

    public BasicDtos.QuestionView toQuestionView(Question question) {
        return new BasicDtos.QuestionView(
                question.getId(),
                question.getTitle(),
                question.getType(),
                question.getSubject(),
                question.getCourseCode(),
                question.getCourseName(),
                question.getChapter(),
                question.getSection(),
                question.getKnowledgeModule(),
                question.getKnowledgePoint(),
                question.getDifficulty(),
                question.getCognitiveLevel(),
                question.getSource(),
                readStringList(question.getTagsJson()),
                readStringList(question.getOptionsJson()),
                question.getCorrectAnswer(),
                question.getScore(),
                question.getEstimatedMinutes(),
                question.getExplanation()
        );
    }

    public BasicDtos.QuestionView fromQuestionViewJson(String json) {
        try {
            return objectMapper.readValue(json, BasicDtos.QuestionView.class);
        } catch (Exception e) {
            throw new IllegalStateException("Question snapshot parse failed", e);
        }
    }

    public BasicDtos.ExamSummary toExamSummary(ExamPaper paper, List<String> targetClasses) {
        return new BasicDtos.ExamSummary(
                paper.getId(),
                paper.getTitle(),
                paper.getDurationMinutes(),
                paper.getPassScore(),
                paper.getStartTime(),
                paper.getEndTime(),
                paper.getPublished(),
                paper.getAutoGenerated(),
                paper.getTotalScore(),
                targetClasses
        );
    }
}
