package com.examonline.service;

import com.examonline.domain.ExamPaper;
import com.examonline.domain.Question;
import com.examonline.web.dto.BasicDtos;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

@Component
public class JsonSupport {
    private final ObjectMapper objectMapper;

    public JsonSupport(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("JSON serialize failed", e);
        }
    }

    public List<String> readStringList(String json) {
        if (json == null || json.isBlank()) {
            return List.of();
        }
        try {
            return objectMapper.readValue(json, new TypeReference<>() {});
        } catch (Exception e) {
            throw new IllegalStateException("JSON parse failed", e);
        }
    }

    public List<String> readTargetClasses(String json) {
        return normalizeTargetClasses(readStringList(json));
    }

    public List<String> normalizeTargetClasses(List<String> targetClasses) {
        if (targetClasses == null || targetClasses.isEmpty()) {
            return List.of();
        }
        List<String> values = targetClasses.stream()
                .filter(Objects::nonNull)
                .map(String::trim)
                .filter(value -> !value.isBlank())
                .toList();
        if (values.isEmpty() || values.stream().anyMatch(this::isAllClassesToken)) {
            return List.of();
        }
        return List.copyOf(new LinkedHashSet<>(values));
    }

    private boolean isAllClassesToken(String value) {
        String normalized = value.replaceAll("\\s+", "").toLowerCase(Locale.ROOT);
        return normalized.equals("*")
                || normalized.equals("all")
                || normalized.equals("全部")
                || normalized.equals("全部班级")
                || normalized.equals("所有班级");
    }

    public BasicDtos.QuestionView toQuestionView(Question question) {
        return new BasicDtos.QuestionView(
                question.getId(),
                question.getTitle(),
                question.getType(),
                question.getSubject(),
                question.getCourseCode(),
                question.getCourseName(),
                question.getChapter(),
                question.getSection(),
                question.getKnowledgeModule(),
                question.getKnowledgePoint(),
                question.getDifficulty(),
                question.getCognitiveLevel(),
                question.getSource(),
                readStringList(question.getTagsJson()),
                readStringList(question.getOptionsJson()),
                question.getCorrectAnswer(),
                question.getScore(),
                question.getEstimatedMinutes(),
                question.getExplanation()
        );
    }

    public BasicDtos.QuestionView fromQuestionViewJson(String json) {
        try {
            return objectMapper.readValue(json, BasicDtos.QuestionView.class);
        } catch (Exception e) {
            throw new IllegalStateException("Question snapshot parse failed", e);
        }
    }

    public BasicDtos.ExamSummary toExamSummary(ExamPaper paper, List<String> targetClasses) {
        return new BasicDtos.ExamSummary(
                paper.getId(),
                paper.getTitle(),
                paper.getDurationMinutes(),
                paper.getPassScore(),
                paper.getStartTime(),
                paper.getEndTime(),
                paper.getPublished(),
                paper.getAutoGenerated(),
                paper.getTotalScore(),
                targetClasses
        );
    }
}
