package com.examonline.service;

import com.examonline.common.BadRequestException;
import com.examonline.common.NotFoundException;
import com.examonline.domain.ExamPaper;
import com.examonline.domain.PaperQuestion;
import com.examonline.domain.Question;
import com.examonline.repo.ExamPaperRepository;
import com.examonline.repo.PaperQuestionRepository;
import com.examonline.repo.QuestionRepository;
import com.examonline.web.dto.BasicDtos;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

@Service
public class PaperService {
    private final ExamPaperRepository paperRepository;
    private final PaperQuestionRepository paperQuestionRepository;
    private final QuestionRepository questionRepository;
    private final JsonSupport jsonSupport;
    private final LogService logService;

    public PaperService(ExamPaperRepository paperRepository,
                        PaperQuestionRepository paperQuestionRepository,
                        QuestionRepository questionRepository,
                        JsonSupport jsonSupport,
                        LogService logService) {
        this.paperRepository = paperRepository;
        this.paperQuestionRepository = paperQuestionRepository;
        this.questionRepository = questionRepository;
        this.jsonSupport = jsonSupport;
        this.logService = logService;
    }

    public List<BasicDtos.ExamSummary> list() {
        return paperRepository.findAll().stream()
                .map(paper -> jsonSupport.toExamSummary(paper, jsonSupport.readStringList(paper.getTargetClassesJson())))
                .toList();
    }

    public BasicDtos.ExamSummary get(Long id) {
        ExamPaper paper = paperRepository.findById(id).orElseThrow(() -> new NotFoundException("试卷不存在"));
        return jsonSupport.toExamSummary(paper, jsonSupport.readStringList(paper.getTargetClassesJson()));
    }

    public List<PaperQuestion> items(Long paperId) {
        return paperQuestionRepository.findByPaperIdOrderByOrderNoAsc(paperId);
    }

    @Transactional
    public BasicDtos.ExamSummary createManual(BasicDtos.PaperManualRequest request, String actor) {
        if (request.title() == null || request.title().isBlank()) {
            throw new BadRequestException("试卷标题不能为空");
        }
        if (request.questionIds() == null || request.questionIds().isEmpty()) {
            throw new BadRequestException("请选择至少一道题");
        }
        List<Question> questions = questionRepository.findAllById(request.questionIds());
        if (questions.isEmpty()) {
            throw new BadRequestException("题目不存在");
        }

        ExamPaper paper = new ExamPaper();
        paper.setTitle(request.title());
        paper.setDurationMinutes(request.durationMinutes() == null ? 60 : request.durationMinutes());
        paper.setPassScore(request.passScore() == null ? 60 : request.passScore());
        paper.setStartTime(request.startTime());
        paper.setEndTime(request.endTime());
        paper.setPublished(false);
        paper.setAutoGenerated(false);
        paper.setTargetClassesJson(jsonSupport.toJson(request.targetClasses() == null ? List.of() : request.targetClasses()));
        paper = paperRepository.save(paper);

        int total = 0;
        paperQuestionRepository.deleteByPaperId(paper.getId());
        for (int i = 0; i < questions.size(); i++) {
            Question question = questions.get(i);
            PaperQuestion item = new PaperQuestion();
            item.setPaperId(paper.getId());
            item.setQuestionId(question.getId());
            item.setOrderNo(i + 1);
            int score = request.questionScores() != null && request.questionScores().size() > i && request.questionScores().get(i) != null
                    ? request.questionScores().get(i)
                    : question.getScore();
            item.setScore(score);
            item.setQuestionSnapshotJson(jsonSupport.toJson(jsonSupport.toQuestionView(question)));
            paperQuestionRepository.save(item);
            total += score;
        }
        paper.setTotalScore(total);
        paperRepository.save(paper);
        logService.record(actor, "CREATE", "PAPER", String.valueOf(paper.getId()), paper.getTitle());
        return jsonSupport.toExamSummary(paper, jsonSupport.readStringList(paper.getTargetClassesJson()));
    }

    @Transactional
    public BasicDtos.ExamSummary createAuto(BasicDtos.PaperAutoRequest request, String actor) {
        if (request.title() == null || request.title().isBlank()) {
            throw new BadRequestException("试卷标题不能为空");
        }
        if (request.questionCount() == null || request.questionCount() <= 0) {
            throw new BadRequestException("题目数量必须大于0");
        }
        List<Question> pool = new ArrayList<>(questionRepository.findAll());
        pool.removeIf(q -> !matches(request.subject(), q.getSubject()));
        pool.removeIf(q -> !matches(request.courseCode(), q.getCourseCode()));
        pool.removeIf(q -> !matches(request.courseName(), q.getCourseName()));
        pool.removeIf(q -> !matches(request.chapter(), q.getChapter()));
        pool.removeIf(q -> !matches(request.section(), q.getSection()));
        pool.removeIf(q -> !matches(request.knowledgeModule(), q.getKnowledgeModule()));
        pool.removeIf(q -> !matches(request.knowledgePoint(), q.getKnowledgePoint()));
        pool.removeIf(q -> !matches(request.difficulty(), q.getDifficulty()));
        pool.removeIf(q -> !matches(request.type(), q.getType()));
        pool.removeIf(q -> !matches(request.cognitiveLevel(), q.getCognitiveLevel()));
        pool.removeIf(q -> !matches(request.source(), q.getSource()));
        pool.removeIf(q -> !hasAllTags(request.tags(), jsonSupport.readStringList(q.getTagsJson())));
        Collections.shuffle(pool, new Random());
        if (pool.isEmpty()) {
            throw new BadRequestException("没有可用于组卷的题目");
        }

        ExamPaper paper = new ExamPaper();
        paper.setTitle(request.title());
        paper.setDurationMinutes(request.durationMinutes() == null ? 60 : request.durationMinutes());
        paper.setPassScore(request.passScore() == null ? 60 : request.passScore());
        paper.setStartTime(request.startTime());
        paper.setEndTime(request.endTime());
        paper.setPublished(false);
        paper.setAutoGenerated(true);
        paper.setTargetClassesJson(jsonSupport.toJson(request.targetClasses() == null ? List.of() : request.targetClasses()));
        paper = paperRepository.save(paper);

        int total = 0;
        paperQuestionRepository.deleteByPaperId(paper.getId());
        for (int i = 0; i < Math.min(request.questionCount(), pool.size()); i++) {
            Question question = pool.get(i);
            PaperQuestion item = new PaperQuestion();
            item.setPaperId(paper.getId());
            item.setQuestionId(question.getId());
            item.setOrderNo(i + 1);
            item.setScore(question.getScore());
            item.setQuestionSnapshotJson(jsonSupport.toJson(jsonSupport.toQuestionView(question)));
            paperQuestionRepository.save(item);
            total += question.getScore();
        }
        paper.setTotalScore(total);
        paperRepository.save(paper);
        logService.record(actor, "AUTO_CREATE", "PAPER", String.valueOf(paper.getId()), paper.getTitle());
        return jsonSupport.toExamSummary(paper, jsonSupport.readStringList(paper.getTargetClassesJson()));
    }

    @Transactional
    public BasicDtos.ExamSummary publish(Long paperId, List<String> targetClasses, String actor) {
        ExamPaper paper = paperRepository.findById(paperId).orElseThrow(() -> new NotFoundException("试卷不存在"));
        paper.setPublished(true);
        if (targetClasses != null) {
            paper.setTargetClassesJson(jsonSupport.toJson(targetClasses));
        }
        paperRepository.save(paper);
        logService.record(actor, "PUBLISH", "PAPER", String.valueOf(paper.getId()), paper.getTitle());
        return jsonSupport.toExamSummary(paper, jsonSupport.readStringList(paper.getTargetClassesJson()));
    }

    @Transactional
    public void delete(Long id, String actor) {
        ExamPaper paper = paperRepository.findById(id).orElseThrow(() -> new NotFoundException("试卷不存在"));
        paperQuestionRepository.deleteByPaperId(id);
        paperRepository.delete(paper);
        logService.record(actor, "DELETE", "PAPER", String.valueOf(id), paper.getTitle());
    }

    private boolean matches(String expected, String actual) {
        return expected == null || expected.isBlank() || (actual != null && expected.equalsIgnoreCase(actual));
    }

    private boolean hasAllTags(List<String> expected, List<String> actual) {
        if (expected == null || expected.isEmpty()) {
            return true;
        }
        List<String> normalized = actual.stream().map(String::toLowerCase).toList();
        return expected.stream()
                .filter(tag -> tag != null && !tag.isBlank())
                .allMatch(tag -> normalized.contains(tag.trim().toLowerCase()));
    }
}
