package com.examonline.web.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;
import java.util.List;

public final class BasicDtos {
    private BasicDtos() {}

    public record LoginRequest(@NotBlank String username, @NotBlank String password) {}
    public record ChangePasswordRequest(@NotBlank String username, @NotBlank String oldPassword, @NotBlank String newPassword) {}
    public record UserRequest(Long id, String username, String password, String role, String realName, String studentNo, String employeeNo, String className, String department, String major, Boolean enabled) {}
    public record ClassRequest(Long id, String name, String department, String major, Integer studentCount) {}
    public record QuestionRequest(Long id, String title, String type, String subject, String courseCode, String courseName, String chapter, String section, String knowledgeModule, String knowledgePoint, String difficulty, String cognitiveLevel, String source, List<String> tags, List<String> options, String correctAnswer, Integer score, Integer estimatedMinutes, String explanation, String creatorUsername) {}
    public record PaperManualRequest(String title, Integer durationMinutes, Integer passScore, LocalDateTime startTime, LocalDateTime endTime, List<Long> questionIds, List<Integer> questionScores, List<String> targetClasses) {}
    public record PaperAutoRequest(String title, Integer durationMinutes, Integer passScore, LocalDateTime startTime, LocalDateTime endTime, String subject, String courseCode, String courseName, String chapter, String section, String knowledgeModule, String knowledgePoint, String difficulty, String type, String cognitiveLevel, String source, List<String> tags, Integer questionCount, List<String> targetClasses) {}
    public record PublishExamRequest(List<String> targetClasses) {}
    public record SaveAnswerRequest(@NotNull Long questionId, String answerText) {}
    public record ReviewAnswerRequest(@NotNull Long questionId, @NotNull Integer score, Boolean correct) {}
    public record ExtendAttemptRequest(Integer minutes) {}
    public record StartExamResponse(Long attemptId, Long paperId, String paperTitle, Integer durationMinutes, Integer switchLimit, Integer totalScore, LocalDateTime deadlineTime, long remainingSeconds, List<QuestionView> questions) {}
    public record QuestionView(Long id, String title, String type, String subject, String courseCode, String courseName, String chapter, String section, String knowledgeModule, String knowledgePoint, String difficulty, String cognitiveLevel, String source, List<String> tags, List<String> options, String correctAnswer, Integer score, Integer estimatedMinutes, String explanation) {}
    public record AttemptView(Long attemptId, Long paperId, String paperTitle, String studentUsername, String className, String status, Integer score, Integer totalScore, Boolean passed, Boolean suspicious, Integer switchCount, LocalDateTime startTime, LocalDateTime submitTime, LocalDateTime deadlineTime, long durationSeconds, long remainingSeconds, Boolean needsReview, List<AnswerView> answers) {}
    public record AnswerView(Long questionId, String title, String type, String subject, String courseCode, String courseName, String chapter, String section, String knowledgeModule, String knowledgePoint, String difficulty, String cognitiveLevel, String source, List<String> tags, String correctAnswer, String explanation, String answerText, Boolean correct, Integer score, Integer maxScore, Boolean reviewed) {}
    public record StatsView(long userCount, long teacherCount, long studentCount, long classCount, long questionCount, long publishedPaperCount, long attemptCount, long activeAttemptCount) {}
    public record LogView(Long id, String actorUsername, String action, String targetType, String targetId, String detail, LocalDateTime createdAt) {}
    public record ExamSummary(Long id, String title, Integer durationMinutes, Integer passScore, LocalDateTime startTime, LocalDateTime endTime, Boolean published, Boolean autoGenerated, Integer totalScore, List<String> targetClasses) {}
    public record AnalyticsView(Double averageScore, Integer maxScore, Integer minScore, Double passRate, long attemptCount, long reviewPendingCount, long suspiciousCount, List<QuestionRate> questionRates, List<ClassScoreView> classScores, List<KnowledgePointView> knowledgePoints) {}
    public record ExamMonitorView(Long paperId, String title, long attemptCount, long activeCount, long submittedCount, long suspiciousCount, long reviewPendingCount, List<MonitorAttemptView> attempts) {}
    public record MonitorAttemptView(Long attemptId, String studentUsername, String className, String status, Integer score, Integer totalScore, Boolean suspicious, Integer switchCount, LocalDateTime startTime, LocalDateTime submitTime, LocalDateTime deadlineTime, long remainingSeconds, Boolean needsReview) {}
    public record QuestionRate(Long questionId, String title, String subject, String courseName, String chapter, String knowledgeModule, String knowledgePoint, Double correctRate, long answeredCount, long correctCount) {}
    public record ClassScoreView(String className, Double averageScore, long attemptCount, Double passRate) {}
    public record KnowledgePointView(String knowledgePoint, Double correctRate, long answeredCount) {}
    public record WrongBookView(Long questionId, String title, String type, String subject, String courseCode, String courseName, String chapter, String section, String knowledgeModule, String knowledgePoint, String difficulty, String cognitiveLevel, String source, List<String> tags, List<String> options, String correctAnswer, Integer wrongCount) {}
    public record StudentStatsView(List<ScorePoint> trend, long attemptCount, double averageScore, long suspiciousCount, List<KnowledgePointView> knowledgePoints) {}
    public record ScorePoint(String label, Integer score) {}
    public record ImportResult(int inserted, int skipped) {}
}
